version: '3'

networks:
  birdboard_laravel:

services:
  nginx:
    image: nginx:stable-alpine
    container_name: birdboard_laravel_nginx
    ports:
      - "8088:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
    networks:
      - birdboard_laravel
  
  mysql:
    image: mysql:5.7.22
    container_name: birdboard_laravel_mysql
    restart: unless-stopped
    tty: true
    ports:
     - "4306:3306"
    volumes:
     - ./mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: birdboard_laravel
      MYSQL_USER: diegovilla
      MYSQL_PASSWORD: birdboard_laravel
      MYSQL_ROOT_PASSWORD: birdboard_laravel
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - birdboard_laravel
  
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: birdboard_laravel_php
    volumes:
      - ./src:/var/www/html
    ports:
      - "9000:9000"
    networks:
      - birdboard_laravel

  composer:
    image: composer:latest
    container_name: birdboard_laravel_composer
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    networks: 
      - birdboard_laravel

  npm:
    image: node:13.7
    container_name: birdboard_laravel_npm
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    entrypoint: ['npm']
    networks: 
      - birdboard_laravel

  artisan:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: birdboard_laravel_artisan
    volumes:
      - ./src:/var/www/html
    depends_on:
      - mysql
    working_dir: /var/www/html
    entrypoint: ['/var/www/html/artisan']
    networks: 
      - birdboard_laravel
