version: '3'

networks:
  birdbord_laravel:

services:
  nginx:
    image: nginx:stable-alpine
    container_name: birdbord_laravel_nginx
    ports:
      - "8088:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
    networks:
      - birdbord_laravel
  
  mysql:
    image: mysql:5.7.22
    container_name: birdbord_laravel_mysql
    restart: unless-stopped
    tty: true
    ports:
     - "4306:3306"
    volumes:
     - ./mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: birdbord_laravel
      MYSQL_USER: diegovilla
      MYSQL_PASSWORD: birdbord_laravel
      MYSQL_ROOT_PASSWORD: birdbord_laravel
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - birdbord_laravel
  
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: birdbord_laravel_php
    volumes:
      - ./src:/var/www/html
    ports:
      - "9000:9000"
    networks:
      - birdbord_laravel
